dotnet run -c debug -- \
  --log=INFO \
  --datadir=./execution-data \
  --config=none.cfg \
  --Init.ChainSpecPath=./chainspec.json \
  --Init.WebSocketsEnabled=true \
  --JsonRpc.Enabled=true \
  --JsonRpc.EnabledModules=net,eth,consensus,subscribe,web3,admin \
  --JsonRpc.Host=0.0.0.0 \
  --JsonRpc.Port=8545 \
  --JsonRpc.WebSocketsPort=8546 \
  --JsonRpc.EngineHost=0.0.0.0 \
  --JsonRpc.EnginePort=8551 \
  --Network.ExternalIp=127.0.0.1 \
  --Network.DiscoveryPort=30303 \
  --Network.P2PPort=30303 \
  --Metrics.Enabled=true \
  --Metrics.ExposePort=9001 \
